defaultspeed: 1.0 # normal speed default: 1.0
maxspeed: 1.5 # speedmode speed default: 1.5
nyan_change_speed: 20 # how fast the color should change in ticks (20 ticks = 1 sec)
entity_check_radius: 10 # the radius it look for entitys to ride
check_for_updates: true
msgs:
    speedmode_activated: 'Speed Mode activated'
    speedmode_deactivated: 'Speed Mode deactivated'
    speedmode_no_perm: 'You are not allowed to use the speed mode!'
    flymode_activated: 'Fly Mode activated'
    flymode_deactivated: 'Fly Mode deactivated'
    flymode_no_perm: 'You are not allowed to use the fly mode!'
    controlmode_activated: 'Control Mode activated'
    controlmode_deactivated: 'Control Mode deactivated'
    controlmode_no_perm: 'You are not allowed to use the control mode!'
    nyan_no_sheep: 'You have to ride a sheep to use that command!'
    nyan_no_perm: 'You are not allowed to use the nyan cat mode!'
    ride: 'You are now riding a '
    ride_hop_off: 'Now u can walk on your own feeds again'
    ride_no_near: 'There is not mob in a radius of %0% blocks that you allowed to ride!'
    ride_dragon: 'You are now riding a EnderDragon!'
    ride_giant: 'You are now riding a Giant!'
    ride_player: 'You are now riding %0%'
    ride_player_no_perm: 'You are not allowed to ride %0%!'
    update_available_1: 'An update is available: '
    update_available_2: 'Type /ridethamob update if you would like to update.'
    update_failed: 'Error while updating! '
    update_success: 'Plugin updated! Please restart your server!'
    update_start: 'Starting Update. This may take a little while!'
    update_up_to_date: 'You have to already have newest version!'
    config_reloaded: 'Config reloaded'
    no_perm: 'You are not allowed to use that command!'
    updater_no_perm: 'You are not allowed to use the updater!'
    command_not_found: 'Command not found!'
    too_many_args: 'Too much arguments!'
# De Version:
# msgs:
    # speedmode_activated: 'Speed Modus aktiviert'
    # speedmode_deactivated: 'Speed Modus deaktiviert'
    # speedmode_no_perm: 'Du hast keinen Zufriff auf den Speed Modus!'
    # flymode_activated: 'Fly Modus aktiviert'
    # flymode_deactivated: 'Fly Modus deaktiviert'
    # flymode_no_perm: 'Du hast keinen Zufriff auf den Fly Modus!'
    # controlmode_activated: 'Control Modus aktiviert'
    # controlmode_deactivated: 'Control Modus deaktiviert'
    # controlmode_no_perm: 'Du hast keinen Zufriff auf den Control Modus!'
    # nyan_no_sheep: 'Du bist nicht auf einem Schaf!'
    # nyan_no_perm: 'Du hast keinen Zufriff auf den Nyan Cat Modus!'
    # ride: 'Du reitest jetzt ein(e)'
    # ride_hop_off: 'Du kann nun wieder alleine gehen :D'
    # ride_no_near: 'Es ist kein Reittier im Umkreis von 10 Blöcken, dass du reiten darfst!'
    # ride_dragon: 'Du reitest jetzt einen Enderdrachen!'
    # ride_giant: 'Du reitest jetzt einen Giganten!'
    # ride_player: 'Du reitest jetzt %0%'
    # ride_player_no_perm: 'Du darfst %0% nicht reiten!'
    # update_available_1: 'Es ist ein Update verfügbar: '
    # update_available_2: 'Benutze /ridethamob update wenn du updaten willst.'
    # update_failed: 'Fehler beim Updaten! '
    # update_success: 'Das Plugin wurde erfolgreich Upgedatet! Beim nächsten Neustart wirst du die neuste Version haben'
    # update_start: 'Starte Update. Dies kann eine Weile dauern'
    # update_up_to_date: 'Du hast bereits die neuste Version!'
    # config_reloaded: 'Config neu geladen'
    # no_perm: 'Du hast keinen Zufriff auf diesen Befehl!'
    # updater_no_perm: 'Du hast keinen Zufriff auf den Updater!'
    # command_not_found: 'Befehl nicht gefunden!'
    # too_many_args: 'Zu viele Argumente!'