name: RideThaMob
author: MiniDigger
version: 1.0
main: de.MiniDigger.RideThaMob.RideThaMob
commands:
  RideThaMob:
      description: RideThaMob :D
      usage: /<command> 
      aliases: rtm
permissions:
    ridethamob.*:
        children:
            ridethamob.mob.*: true
            ridethamob.player: true
            ridethamob.speed: true
            ridethamob.control: true
            ridethamob.nyan: true
    ridethamob.mob.*:
        children:
            ridethamob.mob.bat: true
            ridethamob.mob.blaze: true
            ridethamob.mob.cavespider: true
            ridethamob.mob.chicken: true
            ridethamob.mob.cow: true
            ridethamob.mob.creeper: true
            ridethamob.mob.dragon: true
            ridethamob.mob.enderman: true
            ridethamob.mob.ghast: true
            ridethamob.mob.giant: true
            ridethamob.mob.irongolem: true
            ridethamob.mob.magmacube: true
            ridethamob.mob.mushroomcow: true
            ridethamob.mob.ocelot: true
            ridethamob.mob.pig: true
            ridethamob.mob.pigzombie: true
            ridethamob.mob.blaze: true
            ridethamob.mob.sheep: true
            ridethamob.mob.silverfish: true
            ridethamob.mob.skeleton: true
            ridethamob.mob.slime: true
            ridethamob.mob.snowman: true
            ridethamob.mob.spider: true
            ridethamob.mob.squid: true
            ridethamob.mob.villager: true
            ridethamob.mob.witch: true
            ridethamob.mob.wither: true
            ridethamob.mob.zombie: true
    ridethamob.player:
        default: op
    ridethamob.speed:
        default: op
    ridethamob.control:
        default: op
    ridethamob.player:
        default: op
    ridethamob.speed:
        default: op
    ridethamob.mob.bat:
        default: op
    ridethamob.mob.blaze:
        default: op
    ridethamob.mob.cavespider:
        default: op
    ridethamob.mob.chicken:
        default: op
    ridethamob.mob.cow:
        default: op
    ridethamob.mob.creeper:
        default: op
    ridethamob.mob.dragon:
        default: op
    ridethamob.mob.enderman:
        default: op
    ridethamob.mob.ghast:
        default: op
    ridethamob.mob.giant:
        default: op
    ridethamob.mob.irongolem:
        default: op
    ridethamob.mob.magmacube:
        default: op
    ridethamob.mob.mushroomcow:
        default: op
    ridethamob.mob.ocelot:
        default: op
    ridethamob.mob.pig:
        default: op
    ridethamob.mob.pigzombie:
        default: op
    ridethamob.mob.blaze:
        default: op
    ridethamob.mob.sheep:
        default: op
    ridethamob.mob.silverfish:
        default: op
    ridethamob.mob.skeleton:
        default: op
    ridethamob.mob.slime:
        default: op
    ridethamob.mob.snowman:
        default: op
    ridethamob.mob.spider:
        default: op
    ridethamob.mob.squid:
        default: op
    ridethamob.mob.villager:
        default: op
    ridethamob.mob.witch:
        default: op
    ridethamob.mob.wither:
        default: op
    ridethamob.mob.zombie:
        default: op
    ridethamob.nyan:
        default: op
